variable "use_case_name" {}
variable "org" {}
variable "vcs_identifier" {}
variable "oauth_token" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "creator_workspace" {}
variable "tfe_team_developers_id" {}
variable "tfe_team_ops_id" {}
variable "environment" {}
variable "arm_client_id" {}
variable "arm_client_secret" {}
variable "arm_tenant_id" {}
variable "arm_subscription_id" {}
